// Generated by CoffeeScript 1.4.0
(function() {
  var base_uri, create_resource_methods, key, q, request, resolve_uri, resources, rpas_headers,
    __slice = [].slice;

  request = require('request');

  q = require('q');

  resources = {
    users: "users",
    roles: "roles",
    taxonomies: "taxonomies",
    rated_items: "rated_items",
    workflows: "workflows",
    rated_items: "rated_items",
    documents: "documents",
    research_types: "research_types",
    products: "products",
    templates: "templates",
    lists: "lists",
    disclosures: "disclosures",
    disclosure_groups: "disclosure_groups",
    contacts: "contacts",
    contact_groups: "contact_groups",
    data_sources: "data_sources",
    data_types: "data_types"
  };

  base_uri = "http://54.214.50.90";

  rpas_headers = {
    "api-version": "v1",
    "x-its-rpas": null,
    "Accept": "application/json"
  };

  resolve_uri = function() {
    var params, resource;
    resource = arguments[0], params = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return ["" + base_uri + "/" + (resources[resource] || resource), params].join("/");
  };

  exports.config = function(options) {
    var auth_encoded_str, auth_string, deferred;
    deferred = q.defer();
    if (options["api-version"]) {
      rpas_headers["api-version"] = options["api-version"];
    }
    if (options.token) {
      rpas_headers["x-its-rpas"] = options.token;
      q.resolve(options);
    } else {
      if (options.username && options.password) {
        auth_encoded_str = new Buffer("" + options.username + ":" + options.password).toString("base64");
        auth_string = "Basic " + auth_encoded_str;
        request({
          method: "post",
          url: resolve_uri("authenticate"),
          headers: {
            "Authorization": auth_string
          }
        }, function(e, r, b) {
          try {
            b = JSON.parse(b);
            if (b.Auth) {
              rpas_headers["x-its-rpas"] = b.Auth.RequestToken;
              return deferred.resolve(b);
            } else {
              return deferred.reject(e || b);
            }
          } catch (e) {
            return deferred.reject(e || b);
          }
        });
      }
    }
    return deferred.promise;
  };

  create_resource_methods = function(resource) {
    return {
      list: {
        promise: function(query) {
          var deferred;
          deferred = q.defer();
          request({
            url: resolve_uri(resource),
            qs: query,
            headers: rpas_headers,
            json: true
          }, function(e, r, b) {
            if (e) {
              return deferred.reject(e);
            } else {
              return deferred.resolve(b);
            }
          });
          return deferred.promise;
        },
        stream: function(query) {
          return request({
            url: resolve_uri(resource),
            qs: query,
            headers: rpas_headers,
            json: true
          });
        },
        cb: function(query, next) {
          return request({
            url: resolve_uri(resource),
            qs: query,
            headers: rpas_headers
          }, next);
        }
      },
      select: {
        promise: function(id, query) {
          var deferred;
          deferred = q.defer();
          request({
            url: resolve_uri(resource, id),
            qs: query,
            headers: rpas_headers,
            json: true
          }, function(e, r, b) {
            if (e) {
              return deferred.reject(e);
            } else {
              return deferred.resolve(b);
            }
          });
          return deferred.promise;
        },
        stream: function(id, query) {
          return request({
            url: resolve_uri(resource, id),
            qs: query,
            headers: rpas_headers,
            json: true
          });
        },
        cb: function(id, query, next) {
          return request({
            url: resolve_uri(resource, id),
            qs: query,
            headers: rpas_headers
          }, next);
        }
      }
    };
  };

  for (key in resources) {
    exports[key] = create_resource_methods(key);
  }

}).call(this);
